//create function name createCourse
//get title, description, category, createdBy, duration, price from body
//install multer to store image and video
//create multer middleware
// create upload folder to save img and video
// install uuid to generate random id
// get image from file
// create and save course
// check if user is admin or not

import trycatch from "../middleware/trycatch.js";
import { Courses } from "../models/courseModel.js";
import { Lecture } from "../models/lectureModel.js";
import {rm} from 'fs'
import { promisify } from "util";
import fs from "fs";
import { User } from "../models/userModel.js";
import { v4 as uuid } from "uuid";

// export const createCourse = trycatch(async(req,res)=>{
//   const {title, description, category, createdBy, duration, price} =req.body;

//   const image = req.file;

// await Courses.create({
//     title,
//     description,
//     category,
//     createdBy,
//     image: image?.path,
//     duration,
//     price,
// })
// res.status(201).json({
//   message: "Course Created Successfully",
// });
// })

export const createCourse = trycatch(async (req, res) => {
  // 1. Role Check (Only admins can create courses)
  if (req.user.role !== "admin") {
    return res.status(403).json({
      message: "You are not authorized to create courses.",
    });
  }

  const { title, description, category, createdBy, duration, price } = req.body;
  const image = req.file;

  if (!image) return res.status(400).json({ message: "Please upload an image" });

  await Courses.create({
    title,
    description,
    category,
    createdBy,
    image: image.path, // Store the path generated by multer
    duration,
    price,
  });

  res.status(201).json({
    message: "Course Created Successfully",
  });
});

export const addLectures = trycatch(async (req, res) => {
  const course = await Courses.findById(req.params.id);

  if (!course)
    return res.status(404).json({
      message: "No Course with this id",
    });

  const { title, description } = req.body;

  const file = req.file;

  const lecture = await Lecture.create({
    title,
    description,
    video: file?.path,
    course: course._id,
  });

  res.status(201).json({
    message: "Lecture Added",
    lecture,
  });
});

export const deleteLecture = trycatch(async (req, res) => {
  const lecture = await Lecture.findById(req.params.id);

  rm(lecture.video, () => {
    console.log("Video deleted");
  });

  await lecture.deleteOne();

  res.json({ message: "Lecture Deleted" });
});

const unlinkAsync = promisify(fs.unlink);


export const deleteCourse = trycatch(async (req, res) => {
  const course = await Courses.findById(req.params.id);

  const lectures = await Lecture.find({ course: course._id });

await Promise.all(
    lectures.map(async (lecture) => {
      try {
        await unlinkAsync(lecture.video);
      } catch (err) {
        console.log("Video file already deleted or not found");
      }
    })
  );

  rm(course.image, () => {
    console.log("image deleted");
  });

  await Lecture.find({ course: req.params.id }).deleteMany();

  await course.deleteOne();

  await User.updateMany({}, { $pull: { subscription: req.params.id } });

  res.json({
    message: "Course Deleted",
  });
});

// export const getAllStats = trycatch(async (req, res) => {
//   const totalCoures = (await Courses.find()).length;
//   const totalLectures = (await Lecture.find()).length;
//   const totalUsers = (await User.find()).length;

//   const stats = {
//     totalCoures,
//     totalLectures,
//     totalUsers,
//   };

//   res.json({
//     stats,
//   });
// });

export const getAllStats = trycatch(async (req, res) => {
  // Using countDocuments() is much faster than fetching all records and checking .length
  const totalCourses = await Courses.countDocuments();
  const totalLectures = await Lecture.countDocuments();
  const totalUsers = await User.countDocuments();

  res.json({
    stats: { totalCourses, totalLectures, totalUsers },
  });
});

export const getAllUser = trycatch(async (req, res) => {
  const users = await User.find({ _id: { $ne: req.user._id } }).select(
    "-password"
  );

  res.json({ users });
});

export const updateRole = trycatch(async (req, res) => {
  if (req.user.mainrole !== "superadmin")
    return res.status(403).json({
      message: "This endpoint is assign to superadmin",
    });
  const user = await User.findById(req.params.id);

  if (user.role === "user") {
    user.role = "admin";
    await user.save();

    return res.status(200).json({
      message: "Role updated to admin",
    });
  }

  if (user.role === "admin") {
    user.role = "user";
    await user.save();

    return res.status(200).json({
      message: "Role updated",
    });
  }
});